{% set version = "5.0" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-bnlearn
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/bnlearn_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/bnlearn/bnlearn_{{ version }}.tar.gz
  sha256: e786203121980972c33e1e63736cbc218f9aea8f9b37853a6cd3af762c0279a1

build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  skip: true  # [r_base == "4.3"]

requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{ stdlib("c") }}          # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ stdlib("m2w64_c") }}          # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
  run:
    - r-base

test:
  commands:
    - $R -e "library('bnlearn')"           # [not win]
    - "\"%R%\" -e \"library('bnlearn')\""  # [win]

about:
  home: http://www.bnlearn.com/
  license: GPL-2.0-or-later
  summary: Bayesian network structure learning, parameter learning and inference. This package implements constraint-based (PC, GS, IAMB, Inter-IAMB, Fast-IAMB, MMPC, Hiton-PC), pairwise (ARACNE and Chow-Liu), score-based (Hill-Climbing and Tabu Search) and hybrid (MMHC and RSMAX2) structure learning algorithms for discrete,
    Gaussian and conditional Gaussian networks, along with many score functions and conditional independence tests. The Naive Bayes and the Tree-Augmented Naive Bayes (TAN) classifiers are also implemented. Some utility functions (model comparison and manipulation, random data generation, arc orientation testing, simple
    and advanced plots) are included, as well as support for parameter estimation (maximum likelihood and Bayesian) and inference, conditional probability queries and cross-validation. Development snapshots with the latest bugfixes are available from <http://www.bnlearn.com>.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r
    - MathiasHaudgaard
    - FrodePedersen
    - ArneKr

# Package: bnlearn
# Type: Package
# Title: Bayesian Network Structure Learning, Parameter Learning and Inference
# Version: 4.4.1
# Date: 2019-03-05
# Depends: R (>= 2.14.0), methods
# Suggests: parallel, graph, Rgraphviz, lattice, gRain, ROCR, Rmpfr, gmp
# Author: Marco Scutari [aut, cre], Robert Ness [ctb]
# Maintainer: Marco Scutari <marco.scutari@gmail.com>
# Description: Bayesian network structure learning, parameter learning and inference. This package implements constraint-based (PC, GS, IAMB, Inter-IAMB, Fast-IAMB, MMPC, Hiton-PC), pairwise (ARACNE and Chow-Liu), score-based (Hill-Climbing and Tabu Search) and hybrid (MMHC and RSMAX2) structure learning algorithms for discrete, Gaussian and conditional Gaussian networks, along with many score functions and conditional independence tests. The Naive Bayes and the Tree-Augmented Naive Bayes (TAN) classifiers are also implemented. Some utility functions (model comparison and manipulation, random data generation, arc orientation testing, simple and advanced plots) are included, as well as support for parameter estimation (maximum likelihood and Bayesian) and inference, conditional probability queries and cross-validation. Development snapshots with the latest bugfixes are available from <http://www.bnlearn.com>.
# URL: http://www.bnlearn.com/
# License: GPL (>= 2)
# LazyData: yes
# NeedsCompilation: yes
# Packaged: 2019-03-05 15:57:40 UTC; scutari
# Repository: CRAN
# Date/Publication: 2019-03-05 22:00:03 UTC
