travis:
  secure:
    BINSTAR_TOKEN: G0sXyNWP4rnvHeAd+OWMapgmb/hYDoIoDJgT9NNe+Xhiezs3eJoMUPHRZnQz7gUi7cJcEfveaElZSaJzO3e1uKYkVW3zFQ4EYU23BZe/L73HYDLLKLP/do+KZae4SIEAXd0mWXpbVVGMolidTdL47KJKA21OI6Kucis2Ln3GNDqZeEnPGADlu8p0tWR6JB3wke3wA2T1oBoKvMuMSouCIhwTsQI/2X4OJnqr/PdGlvFeF4LUWN6iX31tuOZytTEi0tQpkdpeWcwtsjMznaT6OrFqM5RPi79gcc8s3tHMnMHPoB45RHvQLRe7McHuZhP1T1DPfo0gxbw/V621D+PqhxCa8a7N3UogVrqdJGxQPtmgFJyYfm2ODoXFVBG5Wct0qGN1nl167GWDbVkX0qbVbP7DRk2l8egwnjqv/68TMv5osbD0jTMyKfFLVBt4ZevLx5sSgCTxvFCCdANz42vwZUKWvXekQALsn8LuCPSSMEt166NVowYj2JG09P+38eoIFSZWCZ7Tzp+uxAyWRD9KhLf2S3LGYAEIeFfiXsgDZ+47Oa0Q2lf3SoOybRFIcjUVQNPz3fLGPBZR8PMX/U+bXohhEBrMNuP6k7mUEqXqNnix9+WBXvqvzP2PR6ftt34zSyph2b+YXwvNFnRAq8QpNkxu12VDpTJ9yaHzLJ4cDRE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
