appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: LWeP6QS7WTB44uAlUlRn4RAdBOJi1lJjh0tD3nf3X0mYbGTmOTxnsgRVVdOiGQR4BVcH+dLzzyc7m5egHsTKR6ywYsGK9OjoZrl0JCqY4E5ZtxgLoMPKC6C9ZT03kVBkvnpWYb2xS4ouKlf7TbeMkp4yClq1TSrNmALOFLhvnGCYlrsS7PNDegBbGLuXLIMsptu4NFaLYFCUmeWk1svjv3LegwGr93uxZML3FwVjMUr0cZMCmo8i8vBDkCr5LTds5MO+ZoY493SbfSzNjoj+ChEVpTOinv8CynIff0SVOgBbow+R1674rkg8/BbF3C3FN/NCRkZLkc4ccQWTKsnoXtOA3WRp91QL/ZhtRSYLrOqsn04c8PsWQ/7fyz4bICGVyCN6po/nlje1FbEqp7sjgxDS0aW09SSnX3JYkH+KsOru5DNRJmsgJWD9+ux4FzvTny75Kw/1oUWN1cgN9dRZWbc1iVEcyuTOFUZLRsvPIYMewsgYOepZDHvck+84qwE+BMZ49HIuPXJ894N4lJHf8NigUhgXvYIC5vngphMDVXLybszKAUGAOt8rkU0h2Xi2A1dJdxWhD6bHADZ7TqQjNTIblxLMfVfjqMGIH76PK0KyWW891zRfbtypaAnB+O7Uzr9cEma7be8UYPl1VPBlXZVm7GQc+zNcPJzxP3hCdHU=
