travis:
  secure:
    BINSTAR_TOKEN: YCPKS2h9bqSutCWGJoGOtrlywEMi2QtrTH3wRbvFJaWKJ0li1elGJYXC9qCVM+nRmhgEwNVHJeI2nBqXx6TE/3OMDHssa+O2fWugFJLhKwjxFGJnEGNFyMU1X1jDv4rBTiSkHKPQyPCROWxPAiYBEVCsCShYfQKAN1HzdhrcbWo4CunhdBi55wU5oiHA78LrsVf9lxSm0mZZ5qDVD0UEC4y99UlRqzu/p5OZ2R4vBwbJ35vySH18UOAGa6yhtRj3Qz20QVtm3t7U21YlLAO93Xaos19Gt5byRTau/qxR0xOx9LwtRiVgiOSLsjpVU0krjxceJTX63/hv+P+C4BinT0l6JSZre8xAFOhyLS/xexMnmBNgk4+YwNPkCSUtwfGba/tZLq+etnaA8nr1DxNi9MA2bmR8r7dJQZ80fKqjk1whQ/wutkDCFNiJ/HEEYg6eGHLPwHi1cgZXkdj7zWXWKJt6gcmYvlZbxJjceDgG3zVFnhZ2Bufa2kfXp8wFGLWfjLPLa+oxJ7TUiFjeTmrDzKyhChrPJWDiPU2DTdPArcfn6UUo6qP3t5r0z6eOn4gXBQ7490uMHgwGOym1EdfxNkXrx0giyovLTOGEYv27v7Nk0ed18I3sC1dmgIpFEJoWxOXpdzkJhL9aBAOZ21WCOeMlC252TGfHPBuPveurLt8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
